### ISSUE TITLE
[QUESTION] New osu! PP update.

### ISSUE THREAD

**Issue by alowave223** [Pure-Peace/peace-performance#3]
Is this package up-to-date with actual osu! PP system?

**Comment by ghost** [comment]
It seems not, but upstream [rosu-pp](https://github.com/MaxOhn/rosu-pp) is up to date.

**Comment by Pure-Peace** [comment]
Hi, sorry I didn't focus on this work for a while.

This repository may no longer be maintained, please use [rosu-pp](https://github.com/MaxOhn/rosu-pp)  (in fact this repository itself is a fork of rosu-pp.)

If you were using [peace-performance-python](https://github.com/Pure-Peace/peace-performance-python) before, you can keep using it as it will be built with the latest code from rosu-pp.

The latest version of [peace-performance-python](https://github.com/Pure-Peace/peace-performance-python) is now 2.0.0.

fixed this
