### ISSUE TITLE
[BUG] Mania PP calculation bug

### ISSUE THREAD

**Issue by def750** [Pure-Peace/peace-performance#4]
Scores in osu!mania with Score V2 + NF have really wierd pp output such as:
![image](https://user-images.githubusercontent.com/23400721/181861030-8ce3e1da-1b5d-4ded-b83f-b795db843977.png)
I'd like to say that max pp on for example Triumph and regret is around 680 (With DT).

**Comment by Pure-Peace** [comment]
Hi, sorry I didn't focus on this work for a while.

This repository may no longer be maintained, please use [rosu-pp](https://github.com/MaxOhn/rosu-pp)  (in fact this repository itself is a fork of rosu-pp.)

If you were using [peace-performance-python](https://github.com/Pure-Peace/peace-performance-python) before, you can keep using it as it will be built with the latest code from rosu-pp.

The latest version of [peace-performance-python](https://github.com/Pure-Peace/peace-performance-python) is now 2.0.0.

fixed this
